package com.igenesys.springoauthexample.model;

public enum ResponseStatus {
	SUCCESS(1),  ERROR(0),  TABLENAMEDOESNOTEXISTS(2),  COLUMNNOTFOUND(3),  INVALIDVALUE(4),  SEARCHNAMECANNOTBEBLANK(5),  LAYERNAMECANNOTBEBLANK(6),  FIELDCANNOTBEBLANK(7),  CREATEDBYCANNOTBEBLANK(8),  IDDOESNOTEXISTS(9),  UNABLETOUPDATEIDDOESNOTEXISTS(10),  DATABASECONNECTIONCLOSE(11),  DUPLCATEVALUE(12),  NOFILESELECTED(13),  FAILEDTOCREATEDIRECTORY(14),  ERRORWHILEUPLOADING(15),  UNABLETOGETFILE(16),  FEATUREIDORLAYERNAMEDOESNOTEXISTS(17),  LAYERCANNOTBEBLANK(18),  OPERATORCANNOTBEBLANK(19),  USERIDCANNOTBEBLANK(20),  DATADOESNOTESXISTS(21),  UNABLETOUPDATED(22),  INCIDENTTYPEIDCANONLYBE1AND2(23),  INVOICENUMBERALREADYEXISTS(24);
	private final int value;
	  
	  private ResponseStatus(int value)
	  {
	    this.value = value;
	  }
	  
	  public int getValue()
	  {
	    return this.value;
	  }
}
